package com.schemavault.app.dto.diff;

public enum DiffStatus {

    IDENTICAL,
    MISSING_IN_TARGET,
    MISSING_IN_SOURCE,
    TYPE_MISMATCH,
    LENGTH_MISMATCH,
    PRECISION_MISMATCH,
    SCALE_MISMATCH,
    NULLABILITY_MISMATCH,
    DEFAULT_MISMATCH,
    PRIMARY_KEY_MISMATCH,
    FOREIGN_KEY_MISMATCH,
    INDEX_MISMATCH,
    CONSTRAINT_MISMATCH,
    DEFINITION_MISMATCH
}
