spring:
  application:
    name: schema-vault-backend

  flyway:
    validate-on-migrate: false

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DRIVER_CLASS_NAME}
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          ssl:
            protocols: TLSv1.2

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

allow:
  cors:
    origin: ${ALLOW_CORS_ORIGIN}

app:
  jwt:
    secret: ${APP_JWT_SECRET}
    expiration-ms: ${APP_JWT_EXPIRATION_MS}
    refresh-expiration-ms: ${APP_JWT_REFRESH_EXPIRATION_MS}
  encryption:
    key: ${APP_ENCRYPTION_KEY}
