spring:
  application:
    name: schema-vault-backend

  flyway:
    validate-on-migrate: false

  springdoc:
    api-docs:
      enabled: false
    swagger-ui:
      enabled: false
      
  allow:
    cors:
      origin: ${ALLOW_CORS_ORIGIN:http://localhost:5173}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://pg-257835b2-tungaeswar12-a902.a.aivencloud.com:13286/schema_vault_db?sslmode=require}
    username: ${SPRING_DATASOURCE_USERNAME:avnadmin}
    password: ${SPRING_DATASOURCE_PASSWORD:AVNS_RS4eTbjiq7iIrY2djmC}
    driver-class-name: ${SPRING_DRIVER_CLASS_NAME:org.postgresql.Driver}

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:tungagnaneswar12@gmail.com}
    password: ${MAIL_PASSWORD:epcuttyklambhciu}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          ssl:
            protocols: TLSv1.2

app:
  jwt:
    secret: ${APP_JWT_SECRET}
    expiration-ms: ${APP_JWT_EXPIRATION_MS:86400000}
    refresh-expiration-ms: ${APP_JWT_REFRESH_EXPIRATION_MS:604800000}
  encryption:
    key: ${APP_ENCRYPTION_KEY}
